<!DOCTYPE html>
<?php //session_start();?>
<html lang="en">
<head>
    <title>Awais Auction Site</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="css/my-Styles.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>

<body>

<div id="main"><!--Get rid of this if you want to cover the content instead of moving it and change container pt to 5-->


    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>


    <!-- Brand -->
    <a class="navbar-brand" href="index.php">Awais' Auctions</a>
        <div class="searchForm">
            <form class="form-inline" id="searchForm" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" name="searchTextBox">
                <button class="btn btn-success" type="submit" name="searchButton">Search</button>
            </form>
        </div>
            <div class="NavLinks">
                <ul class="navbar-nav">
                    <li class="nav-item">
                    <a class="nav-link" href="#">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Basket</a>
                    </li>
        <!-- Dropdown -->
                </ul>
        </div>
</nav>


    <!--Side bar-->
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>
        <a href="controllers/Logout.php"">LogOut</a>
        <button onclick="document.getElementById('id03').style.display='block'" style="width:auto;">Register</button>
        <button onclick="document.getElementById('id02').style.display='block'" style="width:auto;">Auction</button>
        <a href="#">Notifications</a>
        <a href="#">About Us</a>
    </div>


    <!--Login Page-->

<div id="id01" class="modal">
    <form class="modal-content animate" action="/controllers/Login.php" method="post">
        <div class="imgcontainer">
            <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
        </div>

        <div class="container">
            <label for="uname" style="color: #1b1e21"><b>Username</b></label>

            <input type="text" class="form-control" name="username" placeholder="username" required="required"/>

            <label for="psw" style="color: #1b1e21"><b>Password</b></label>
            <input type="password" class="form-control" name="password" placeholder="password" required="required"/>
            <input type="submit" class="btn btn-primary" name="login" value="Login"/>
        </div>

        <div class="container" style="background-color:#f1f1f1">
            <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
        </div>
    </form>
</div>
    <!--Auction Pop Up Form-->
    <div id="id02" class="modal">
        <form class="modal-content animate" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post" enctype="multipart/form-data">
            <div class="imgcontainer">
                <span onclick="document.getElementById('id02').style.display='none'" class="close" title="Close Modal">&times;</span>
            </div>

            <div class="container">
                <input type="hidden" name="size" value="1000000">
                <!--ItmesTable-->
                <label for="TitleName" style="color: #1b1e21"><b>Enter Title Name</b></label>
                <input type="text" class="form-control" name="titleName" placeholder="Title Name" required="required"/>
                <label for="uploadImage" style="color: #1b1e21"><b> Select Item Image</b></label>

                <input type="file" placeholder="Choose an image" name="image" required>
                <br>
                <label for="ItemDescription" style="color: #1b1e21"><b>Enter Item Description</b></label>
                <input type="text" class="form-control" name="titleDescription" placeholder="Title Description" required="required"/>
<!--                <label for="postingUser"><b></b></label>-->
<!--                <input type="hidden" name="postingUser" value="--><?php //echo $_SESSION['username'] ?><!--"/>-->

                <!--AuctionTableTable-->
                <label for="date" style="color: #1b1e21"> <b>Please choose a start date</b></label>
                <input type="text" placeholder="yyyy-mm-dd" name="startDate" required>
                <label for="date" style="color: #1b1e21"> <b>Please choose an end date</b></label>
                <input type="text" placeholder="yyyy-mm-dd" name="endDate" required>

                <input type="submit" class="btn btn-primary" name="enterTitle" value="Enter"/>
            </div>

            <div class="container" style="background-color:#f1f1f1">
                <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
            </div>
        </form>
    </div>

    <div id="id03" class="modal">
        <form class="modal-content animate" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
            <div class="img-container">
                <span onclick="document.getElementById('id03').style.display='none'" class="close" title="Close Modal">&times;</span>
            </div>

            <div class="container">
                <label for="uname" style="color: #1b1e21"><b>Enter Username</b></label>
                <input type="text" class="form-control" name="regUsername" placeholder="username" required="required"/>

                <label for="psw" style="color: #1b1e21"><b>Enter Password</b></label>
                <input type="password" class="form-control" name="regPassword" placeholder="password" required="required"/>

                <label for="psw" style="color: #1b1e21"><b>Enter Name</b></label>
                <input type="text" class="form-control" name="enterName" placeholder="Enter Name" required="required"/>

                <label for="psw" style="color: #1b1e21"><b>Enter Email</b></label>
                <input type="text" class="form-control" name="enterEmail" placeholder="Enter email" required="required"/>

                <input type="submit" class="btn btn-primary" name="register" value="Register"/>
            </div>

            <div class="container" style="background-color:#f1f1f1">
                <button type="button" onclick="document.getElementById('id03').style.display='none'" class="cancelbtn">Cancel</button>
            </div>
        </form>
    </div>

    <h3><?php

        if (isset($_SESSION['username']))
        {
            echo "Welcome to the website " . $_SESSION['username'];
        }
        else
            echo "Welcome to the website";
        ?></h3>

    <script>
        // Get the login form
        var modal = document.getElementById('id01');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>

    <script>
        // Get the login form
        var modal = document.getElementById('id02');

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>

<!--I dont like the bootstrap burger menu, so i did it in java script-->
<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
        document.getElementById("main").style.marginRight = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
        document.getElementById("main").style.marginRight= "0";
    }
</script>

</body>
</html>
